-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-25 02:02:08 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE cruiseroute CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE route CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE worldcruise CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    cabin_no      NUMBER(5) NOT NULL,
    cabin_class   VARCHAR2(6) NOT NULL,
    cabin_capcity NUMBER(3) NOT NULL,
    ship_code     NUMBER(6) NOT NULL,
    manifest_id   NUMBER(6) NOT NULL
);

COMMENT ON COLUMN cabin.cabin_no IS
    'cabin number';

COMMENT ON COLUMN cabin.cabin_class IS
    'cabin class';

COMMENT ON COLUMN cabin.cabin_capcity IS
    'cabin capcity';

COMMENT ON COLUMN cabin.ship_code IS
    'ship code';

COMMENT ON COLUMN cabin.manifest_id IS
    'manifest id';

ALTER TABLE cabin
    ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_no,
                                          cabin_class,
                                          cabin_capcity );

CREATE TABLE cruiseroute (
    cruise_arrival_time DATE NOT NULL,
    cruise_depart_time  DATE NOT NULL,
    cruise_id           NUMBER(6) NOT NULL,
    port_id             NUMBER(6) NOT NULL
);

COMMENT ON COLUMN cruiseroute.cruise_arrival_time IS
    'cruise arrival time';

COMMENT ON COLUMN cruiseroute.cruise_depart_time IS
    'cruise depart time';

ALTER TABLE cruiseroute ADD CONSTRAINT cruiseroute_pk PRIMARY KEY ( cruise_arrival_time,
                                                                    cruise_depart_time );

CREATE TABLE manifest (
    manifest_id   NUMBER(6) NOT NULL,
    manifest_time unknown 
/*  ERROR: Datatype UNKNOWN is not allowed */
     NOT NULL,
    cruise_id     NUMBER(6) NOT NULL,
    passenger_id  NUMBER(6) NOT NULL
);

COMMENT ON COLUMN manifest.manifest_id IS
    'manifest id';

COMMENT ON COLUMN manifest.cruise_id IS
    'cruise id';

CREATE UNIQUE INDEX manifest__idx ON
    manifest (
        cruise_id
    ASC );

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( manifest_id );

CREATE TABLE operator (
    operator_id       NUMBER(6) NOT NULL,
    operator_name     VARCHAR2(10) NOT NULL,
    operator_ceo_name VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN operator.operator_id IS
    'operator id';

COMMENT ON COLUMN operator.operator_name IS
    'operator name';

COMMENT ON COLUMN operator.operator_ceo_name IS
    'operator ceo''s name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( operator_id );

CREATE TABLE passenger (
    passenger_id        NUMBER(6) NOT NULL,
    passenger_firstname VARCHAR2(10) NOT NULL,
    passenger_lastname  VARCHAR2(10) NOT NULL,
    passenger_gender    CHAR(1) NOT NULL,
    passenger_dob       DATE NOT NULL,
    passenger_street_no VARCHAR2(20) NOT NULL,
    passenger_town      CHAR(20) NOT NULL,
    passenger_postcode  NUMBER(10) NOT NULL,
    passenger_country   VARCHAR2(10) NOT NULL,
    passenger_phone_no  VARCHAR2(20) NOT NULL,
    manifest_id         NUMBER(6) NOT NULL
);

ALTER TABLE passenger
    ADD CHECK ( passenger_gender IN ( 'M', 'O', 'W' ) );

COMMENT ON COLUMN passenger.passenger_id IS
    'passenger''s id';

COMMENT ON COLUMN passenger.passenger_firstname IS
    'passenger''s firstname';

COMMENT ON COLUMN passenger.passenger_lastname IS
    'passenger''s lastname';

COMMENT ON COLUMN passenger.passenger_gender IS
    'passenger''s gender M-man W-woman O-other';

COMMENT ON COLUMN passenger.passenger_dob IS
    'passenger''s date of birth';

COMMENT ON COLUMN passenger.passenger_street_no IS
    'passenger''s street number';

COMMENT ON COLUMN passenger.passenger_town IS
    'passenger''s town';

COMMENT ON COLUMN passenger.passenger_postcode IS
    'passenger''s postcode';

COMMENT ON COLUMN passenger.passenger_country IS
    'passenger''s country';

COMMENT ON COLUMN passenger.passenger_phone_no IS
    'passenger''s phone number';

COMMENT ON COLUMN passenger.manifest_id IS
    'manifest id';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id );

CREATE TABLE port (
    port_id         NUMBER(6) NOT NULL,
    port_name       VARCHAR2(20) NOT NULL,
    port_country    VARCHAR2(20) NOT NULL,
    port_population NUMBER(6) NOT NULL,
    port_longtitude NUMBER(4) NOT NULL,
    port_latitude   NUMBER(4) NOT NULL
);

COMMENT ON COLUMN port.port_id IS
    'port id';

COMMENT ON COLUMN port.port_country IS
    'port country';

COMMENT ON COLUMN port.port_population IS
    'port porpulation';

COMMENT ON COLUMN port.port_longtitude IS
    'port longtitude';

COMMENT ON COLUMN port.port_latitude IS
    'port latitide';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_id );

CREATE TABLE route (
    port_id             NUMBER(6) NOT NULL,
    cruise_arrival_time DATE NOT NULL,
    cruise_depart_time  DATE NOT NULL
);

COMMENT ON COLUMN route.port_id IS
    'port id';

COMMENT ON COLUMN route.cruise_arrival_time IS
    'cruise arrival time';

COMMENT ON COLUMN route.cruise_depart_time IS
    'cruise depart time';

ALTER TABLE route
    ADD CONSTRAINT route_pk PRIMARY KEY ( port_id,
                                          cruise_arrival_time,
                                          cruise_depart_time );

CREATE TABLE ship (
    ship_code             NUMBER(6) NOT NULL,
    ship_name             VARCHAR2(20) NOT NULL,
    ship_commisioned_date DATE NOT NULL,
    ship_tonage           NUMBER(4) NOT NULL,
    ship_guest_capacity   NUMBER(6) NOT NULL,
    ship_register_country VARCHAR2(10) NOT NULL,
    operator_id           NUMBER(6) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'ship code';

COMMENT ON COLUMN ship.ship_name IS
    'ship name';

COMMENT ON COLUMN ship.ship_commisioned_date IS
    'ship commissioned date';

COMMENT ON COLUMN ship.ship_tonage IS
    'ship tonnage';

COMMENT ON COLUMN ship.ship_guest_capacity IS
    'ship guest capacity';

COMMENT ON COLUMN ship.ship_register_country IS
    'ship register country';

COMMENT ON COLUMN ship.operator_id IS
    'operator id';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE worldcruise (
    cruise_id           NUMBER(6) NOT NULL,
    cruise_description  VARCHAR2(50) NOT NULL,
    cruise_name         VARCHAR2(20) NOT NULL,
    manifest_id         NUMBER(6) NOT NULL,
    cruise_arrival_time DATE NOT NULL,
    cruise_depart_time  DATE NOT NULL,
    ship_code           NUMBER(6) NOT NULL,
    port_id             NUMBER(6) NOT NULL
);

COMMENT ON COLUMN worldcruise.cruise_id IS
    'cruise id';

COMMENT ON COLUMN worldcruise.cruise_description IS
    'cruise description';

COMMENT ON COLUMN worldcruise.cruise_name IS
    'cruise name';

COMMENT ON COLUMN worldcruise.manifest_id IS
    'manifest id';

COMMENT ON COLUMN worldcruise.cruise_arrival_time IS
    'cruise arrival time';

COMMENT ON COLUMN worldcruise.cruise_depart_time IS
    'cruise depart time';

COMMENT ON COLUMN worldcruise.ship_code IS
    'ship code';

COMMENT ON COLUMN worldcruise.port_id IS
    'port id';

CREATE UNIQUE INDEX worldcruise__idx ON
    worldcruise (
        manifest_id
    ASC );

ALTER TABLE worldcruise ADD CONSTRAINT worldcruise_pk PRIMARY KEY ( cruise_id );

ALTER TABLE cruiseroute
    ADD CONSTRAINT cruiseroute_port_fk FOREIGN KEY ( port_id )
        REFERENCES port ( port_id );

ALTER TABLE route
    ADD CONSTRAINT cruiseroute_route FOREIGN KEY ( cruise_arrival_time,
                                                   cruise_depart_time )
        REFERENCES cruiseroute ( cruise_arrival_time,
                                 cruise_depart_time );

ALTER TABLE cruiseroute
    ADD CONSTRAINT cruiseroute_worldcruise_fk FOREIGN KEY ( cruise_id )
        REFERENCES worldcruise ( cruise_id );

ALTER TABLE cabin
    ADD CONSTRAINT manifest_cabin FOREIGN KEY ( manifest_id )
        REFERENCES manifest ( manifest_id );

ALTER TABLE passenger
    ADD CONSTRAINT manifest_passenger FOREIGN KEY ( manifest_id )
        REFERENCES manifest ( manifest_id );

ALTER TABLE manifest
    ADD CONSTRAINT manifest_passenger_fk FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( operator_id )
        REFERENCES operator ( operator_id );

ALTER TABLE route
    ADD CONSTRAINT port_route FOREIGN KEY ( port_id )
        REFERENCES port ( port_id );

ALTER TABLE worldcruise
    ADD CONSTRAINT port_worldcruise FOREIGN KEY ( port_id )
        REFERENCES port ( port_id );

ALTER TABLE worldcruise
    ADD CONSTRAINT relation_15 FOREIGN KEY ( cruise_arrival_time,
                                             cruise_depart_time )
        REFERENCES cruiseroute ( cruise_arrival_time,
                                 cruise_depart_time );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE worldcruise
    ADD CONSTRAINT ship_worldcruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE manifest
    ADD CONSTRAINT worldcruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES worldcruise ( cruise_id );

ALTER TABLE worldcruise
    ADD CONSTRAINT worldcruise_manifestv1 FOREIGN KEY ( manifest_id )
        REFERENCES manifest ( manifest_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             2
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
